# This file is a template for the pre-commit-config.yaml file
# that is used to create the pre-commit configuration.
# The pre-commit-config.yaml file is created in the mamba-githook application
# User can edit this file to add or remove hooks from the pre-commit configuration.
#
# for more information for other options see:
# https://pre-commit.com/#pre-commit-configyaml---top-level
files: \.(py|ipynb)$
repos:
- repo: https://github.com/psf/black
  rev: 21.9b0
  hooks:
  - id: black
    args: ["-l", "132"]
