name: Build Debian Packages and Multi-Platform go installer binaries

on:
  push:
    tags: [ "[0-9]+.[0-9]+.[0-9]+" ]

env:
  DEBEMAIL: "${{ github.actor }}@users.noreply.github.com"
  DEBFULLNAME: "${{ github.actor }}"

jobs:
  build-debian-packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ amd64, arm64, armhf ]
    container:
      image: debian:latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup Debian Package for build Environment
      run: |
        apt-get update -y && apt-get install -y \
        --no-install-recommends \
        build-essential \
        debhelper devscripts lintian \
        && apt-get clean && rm -rf /var/lib/apt/lists/*

    - name: Build Debian Package
      run: debuild --no-lintian -us -uc -b --post-clean -a${{matrix.platform}}

    - name: Copy debian package to workspace
      run: |
        mkdir -p debian-package
        cp ../mamba-githook_*.deb mamba-githook_${{matrix.platform}}.deb

    - name: Upload debian package
      uses: actions/upload-artifact@v4
      with:
        name:  mamba-githook_${{matrix.platform}}.deb
        path: mamba-githook_${{matrix.platform}}.deb

  build-multi-platform:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and run multi-platform builder
      uses: docker/build-push-action@v6
      with:
        context: .
        file: installer/Dockerfile
        push: false
        pull: false
        load: true
        tags: mamba-githook-builder:latest
    - name: Run container and build binaries
      run: |
        mkdir -p ${{ github.workspace }}/_build
        docker run --rm -v ${{ github.workspace }}/_build:/_build mamba-githook-builder
    - name: Upload multi-platform binaries
      run: |
        cd ${{ github.workspace }}/_build
        for file in *; do
          echo "Uploading $file"
          echo "::group::Upload $file"
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/zip" \
            --data-binary "@${file}" \
            "https://uploads.github.com/repos/${{ github.repository }}/actions/artifacts" \
            -o response.json
          cat response.json
          rm response.json
          echo "::endgroup::"
        done

  create-release:
    needs: [build-debian-packages, build-multi-platform]
    runs-on: ubuntu-latest
    steps:
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v4
      continue-on-error: true
    - name: List downloaded artifacts
      run: |
        echo "Downloaded artifacts:"
        find . -type f
    - name: Prepare release assets
      run: |
        mkdir -p release_assets
        find . -type f \( -name "*.deb" -o -name "*.zip" \) -exec cp {} release_assets/ \;
    - name: Display release assets
      run: |
        echo "Release assets:"
        ls -l release_assets/
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: release_assets/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
    - name: Check release creation
      run: |
        if [ $? -eq 0 ]; then
          echo "Release created successfully"
        else
          echo "Failed to create release"
          exit 1
        fi
