name: Build Debian Packages and Multi-Platform go installer binaries

on:
  push:
    tags: [ "[0-9]+.[0-9]+.[0-9]+" ]

env:
  DEBEMAIL: "${{ github.actor }}@users.noreply.github.com"
  DEBFULLNAME: "${{ github.actor }}"

jobs:
  build-debian-packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ amd64, arm64, armhf ]
    container:
      image: debian:latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup Debian Package for build Environment
      run: |
        apt-get update -y && apt-get install -y \
        --no-install-recommends \
        build-essential \
        debhelper devscripts lintian \
        && apt-get clean && rm -rf /var/lib/apt/lists/*

    - name: Build Debian Package
      run: debuild --no-lintian -us -uc -b --post-clean -a${{matrix.platform}}

    - name: Copy debian package to workspace
      run: |
        mkdir -p debian-package
        cp ../mamba-githook_*.deb mamba-githook_${{matrix.platform}}.deb

    - name: Upload debian package
      uses: actions/upload-artifact@v4
      with:
        name:  mamba-githook_${{matrix.platform}}.deb
        path: mamba-githook_${{matrix.platform}}.deb

  build-multi-platform:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and run multi-platform builder
      uses: docker/build-push-action@v6
      with:
        context: .
        file: installer/Dockerfile
        push: false
        pull: false
        load: true
        tags: mamba-githook-builder:latest

    - name: Run container and build binaries
      run: |
        mkdir -p ${{ github.workspace }}/_build
        docker run --rm -v ${{ github.workspace }}/_build:/_build mamba-githook-builder

    - name: Upload multi-platform binaries as split artifacts
      run: |
        cd _build
        for file in *; do
          tar -czf "${file}.tar.gz" "${file}"
          printf "Uploading %s\n" "${file}.tar.gz"
          mv "${file}.tar.gz" "mamba-githook-binary-${file}"
        done
      shell: bash

  create-release:
    needs: [build-debian-packages, build-multi-platform]
    runs-on: ubuntu-latest
    steps:
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v4
    - name: Prepare release assets
      run: |
        mkdir -p release_assets
        mv mamba-githook_*.deb release_assets/
        mv _build/mamba-githook-binary-* release_assets/
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          release_assets/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
